steps:
  # Step 1: Build with environment-specific build command
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA',
      '--build-arg', 'BUILD_ENV=$_ENV',  # Will use dev/uat/prod
      '.'
    ]

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$_IMAGE_NAME-$_ENV',  # Unique name per environment
      '--image', 'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA',
      '--region', 'us-west4',
      '--platform', 'managed',
      '--port', '80',
      '--set-env-vars', 'NODE_ENV=$_ENV',
      '--allow-unauthenticated'
    ]

images:
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA'
