# cloudbuild.yaml

substitutions:
  _ARTIFACT_REPO: react-dev-repo
  _IMAGE_NAME: react-app

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'apply', '-f', 'k8s/deployment.yaml'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-west4'
      - 'CLOUDSDK_COMPUTE_ZONE=us-west4-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=onlineboutique-cluster-960'

images:
  - 'us-west4-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME:$COMMIT_SHA'
